// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc6190.AleksCommandBasedBot.commands;

import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc6190.AleksCommandBasedBot.Robot;
import org.usfirst.frc6190.AleksCommandBasedBot.subsystems.DriveTrain;

/**
 *
 */
public class turnDegrees extends Command {
	
	double degrees;
	boolean end;
	double gyroAngle;

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public turnDegrees() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.driveTrain);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

	// Called just before this Command runs the first time
    protected void initialize() {
    	DriveTrain.SPIGyro2.reset();
        degrees = Robot.uDP.inputValue;
        end = false;
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	
    	//Now loop until you turn the perfect amount!
    	double gyroAngle = DriveTrain.SPIGyro2.getAngle();
        if (gyroAngle < degrees-2 || gyroAngle > degrees+2) {
        	if (gyroAngle < degrees-2) {
        		DriveTrain.driveBase.tankDrive(0.85, -0.85);
        	}
        	if (gyroAngle > degrees+2) {
        		System.out.println("RIGHT!");
        		DriveTrain.driveBase.tankDrive(-0.85, 0.85);
        	}
        	gyroAngle = DriveTrain.SPIGyro2.getAngle();
            System.out.println(gyroAngle);
        } else {
        	System.out.println("NOTHING!");
        	DriveTrain.driveBase.tankDrive(0, 0);
        	DriveTrain.SPIGyro2.reset();
        	end = true;
        }
    }
    

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
    	if (end == true) {
    		return true;
    	} else {
    		return false;
    	}
    }

    // Called once after isFinished returns true
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
